### ISSUE TITLE
Share file via URL

### ISSUE THREAD

**Issue by hansr** [diodechain/dDrive_Alpha_Program#12]
**Description:** Allow sharing of files to someone via link without requiring they install dDrive

**Modification Area:** Share a file should be a central UX item launchable from the main menu.  Can launch the web view to  enable a per file link creation and revocation.  Can be expanded later to have information about the link's usage.  If the file is not already in the Drive (but elsewhere on the computer), it should be copied to the drive.

**Why:** Key frictional action around files is sharing them.  Without dDrive, the file either has to be emailed or uploaded and a link sent.  With dDrive, the file is already on your system and a link can be emailed directly to the file without uploading it (to a central drive or via email).  It is more secure and removes a step.

**Comment by dominicletz** [comment]
Added with v0.7.5
