### ISSUE TITLE
"RemoveMember" operations happening too often

### ISSUE THREAD

**Issue by hansr** [diodechain/dDrive_Alpha_Program#16]
**Operating system and version:**
MacOS Catalina 10.15.4

**dDrive version:**
 v0.7.2-12-gff164c1 and earlier

**Problem description:**
My dDrive instance has logged 17,790 "RemoveMember" operations in the last ~30 days. All "RemoveMember" operations are being attempted on the same drive.

![image](https://user-images.githubusercontent.com/275153/101712582-ce14a480-3ad0-11eb-88bc-27703ee2d581.png)

**NOTE:** v0.7.2-10 and earlier showed many of the transactions were happening to Drive "<Orphaned>".  After v0.7.2-12, all operations are being attributed to the same named drive, so v0.7.2-12 may have fixed a bug that now renders "<Orphaned>" as an actual Drive name.  Or, it could be that the other operations previously attributed to "<Orphaned>" are just not being listed, in which case the fix should also address the situation in which "RemoveMember" operations are happening to "<Orphaned>" drives.

**Steps to reproduce:**
It is uncertain as to the steps to reproduce, but here is a guess:
- Create drive
- Invite peers/members
- Allow drives to sync
- Pull one or more peers offline
- Remove a peer that has been pulled offline
- Maybe even try removing the BNS entry of the peer who is now offline
- Maybe even try having the peer "drop" the drive 

Will attempt to replicate in coming days and provide more concrete steps to repro.

**Comment by dominicletz** [comment]
Fixed with v0.7.2-13
