### ISSUE TITLE
Status of peers is incorrect until Manage Drives menu is opened

### ISSUE THREAD

**Issue by hansr** [diodechain/dDrive_Alpha_Program#17]
MacOS 10.15.4, dDrive version 0.7.2-12

**Description:**
The status of the Peers in the main drop down menu is incorrect until the Manage Drives menu is opened - the main drop-down always shows 0 of N peers until the Manage Drives menu is opened, after which it shows what may be the correct state (or what may be a static state from each time the Manage Drives menu is opened).

**Steps to reproduce:**
* If no peers, share a drive with a Peer (accept it, verify Peer is working) - otherwise, just look at a drive that already has peers
* Ensure the peers are online and actively syncing
* Close dDrive, re-open dDrive
* Open the main menu and observe it shows "0 of 1 Peers Online" for all drives
* Open the Manage Drives menu
* Open the main menu and now observe it shows "1 of 1 Peers Online" (or other valid status) for all drives

**Comment by dominicletz** [comment]
Fixed with v0.8.0
