### ISSUE TITLE
Drop down menu doesn't show drive until Manage menu is opened

### ISSUE THREAD

**Issue by hansr** [diodechain/dDrive_Alpha_Program#2]
Linux ARM (Raspberry Pi), dDrive version 0.7.2

**Description:**
When a drive is shared with the rPi and is accepted, the main menu never shows the drive until the Manage menu is opened.  After the Manage menu is opened, then the main menu lists the drive.

**Steps to reproduce:**
1) Share a drive from system A with a Raspberry Pi running dDrive (system B)
2) Accept the share on system B
3) Observe the menu does not list the drive - not initially, not ever
4) Open the Manage Drives menu
5) Close the Manage Drives menu
6) Open the main menu and observe the menu now lists the shared drive

**Comment by hansr** [comment]
@dominicletz This exists on Mac as well - I guess it is cross-platform.  Both instances I have noticed this on have been with "Early Access" 0.7.2 versions - neither had Dev Mode enabled.  I'm guessing that does not matter, but FYI.

**Comment by dominicletz** [comment]
This is fixed with v0.8.0
