### ISSUE TITLE
"General" tab is missing from "Manage Drives" window (linux)

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/dDrive_Alpha_Program#21]
**OS:** Linux 5.4.0-26-generic x86_64, Linux Mint 20, xfce desktop environment 

**dDrive version:** 0.7.2 (patch version: v0.7.5-4-g9d4825b)

**Problem Description**:
When opening the Manage Drives window, there is no "General" tab shown. "Invites," "Operations," and drive tabs are shown. The information from the "General" tab can still be seen via the web application.

**Steps to Reproduce:**
1. Boot OS
2. Start dDrive from desktop shortcut 
3. Right click tray icon 
4. Select "[account name] - early access" from menu
5. Select "Manage Drives" from second level menu

**Screenshot:**
![MissingGeneralTab](https://user-images.githubusercontent.com/17348062/103670164-2fd30c00-4fb4-11eb-856c-7118e26973d0.PNG)

**Comment by dominicletz** [comment]
Hey @zach-pagel we're migrating most of the general content to the web views, so there is only one place of truth. We will keep native ui elements only where a tight desktop integration is making things better. Let us know your thoughts!

**Comment by zach-pagel** [comment]
Sounds great!
