### ISSUE TITLE
UI Enhancement: Invite to drive popup window can be confusing

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/dDrive_Alpha_Program#22]
**Owner OS:** Linux 5.4.0-26-generic x86_64, Linux Mint 20, xfce desktop environment 
**Peer OS:** Windows 10
**dDrive version:** 0.7.2 (patch version: v0.7.5-4-g9d4825b)

**Description**:
When inviting a peer to a drive, a window pops up which contains a loading bar that passes back and forth across the screen. This gives the user an impression that the program is awaiting a response or processing something. The window does not close when the invitee accepts an invite.

**Suggested Enhancement:**
Have the popup show some sort of indication when an invite is accepted, or remove the loading bar from the popup window. 

**Page/menu or other product area the new feature will impact:** dDrive invite window.

**Use case or business case (why would this be helpful):** Provide more clarity to the user.

**Screenshot:**
![InviteLoadingAfterConfirmation](https://user-images.githubusercontent.com/17348062/103897932-26ba7a00-512f-11eb-91b3-5abf655281a8.png)

**Comment by dominicletz** [comment]
Thanks @zach-pagel ! Will stop the progress gauge with release v0.8.1
