### ISSUE TITLE
Add option to download multiple files in a shared link as a .zip

### ISSUE THREAD

**Issue by kaithenarrator** [diodechain/dDrive_Alpha_Program#24]
Description: When sharing multiple files, it would be nice to have a feature that downloads all of the files in a shared link as a singular compressed .zip folder instead of downloading each file individually. 

Impact: This will most directly impact the link share feature in a positive way. 

Case: For smaller folders it's not a worry, but for folders with tons of files (ie. sharing old image albums) it'd be easier to download them with one click.

**Comment by dominicletz** [comment]
Coming with alpha update 0.9.0 tomorrow

**Comment by dominicletz** [comment]
![Selection_410](https://user-images.githubusercontent.com/2987674/104613541-9f698b00-5687-11eb-9f25-7eaf12b15cc8.png)
