### ISSUE TITLE
Certain usernames immediately crash the signup process

### ISSUE THREAD

**Issue by hansr** [diodechain/dDrive_Alpha_Program#25]
**Operating system and version:**
Raspberry Pi 4 Linux, MacOS 10.15.4, likely all

**dDrive version:**
0.7.2-090

**Problem description:**
Entering certain user names into the "Sign Up" dialog immediately dismisses the dialog and generates errors in the logs.

**Steps to reproduce:**

1. Install dDrive / restart dDrive with a fresh .config/ddrive folder
2. Click Sign Up
3. Enter "AMPi1Diode"
4. Observe the dialog immediately disappears every time that username is entered.  It is not clear what other potential usernames may generate the same issue.

**Logs:**
12:41:40.488 [info] <0.1735.0> Updater no new package.zip
12:41:47.412 [error] Process #PID<0.2034.0> on node :"ddrive@HRs-MacBook" raised an exception
** (ErlangError) Erlang error: {:nocatch, {:merkle_check_failed, "Assert \"key_prefix\" == \"prefix\" failed! (<<1::size(1)>> != <<0::size(1)>>)"}}
    (ddrive 0.7.2) lib/diode_client/shell.ex:175: DiodeClient.Shell.get_account_value/3
    (ddrive 0.7.2) lib/contract/bns.ex:133: Contract.BNS.value/4
    (ddrive 0.7.2) lib/model/domain.ex:50: Model.Domain.lookup_fetch/3
    (ddrive 0.7.2) lib/ui/signup.ex:381: anonymous fn/4 in UI.Signup.handle_cast/2
12:42:08.685 [error] Process #PID<0.2083.0> on node :"ddrive@HRs-MacBook" raised an exception
** (ErlangError) Erlang error: {:nocatch, {:merkle_check_failed, "Assert \"key_prefix\" == \"prefix\" failed! (<<1::size(1)>> != <<0::size(1)>>)"}}
    (ddrive 0.7.2) lib/diode_client/shell.ex:175: DiodeClient.Shell.get_account_value/3
    (ddrive 0.7.2) lib/contract/bns.ex:133: Contract.BNS.value/4
    (ddrive 0.7.2) lib/model/domain.ex:50: Model.Domain.lookup_fetch/3
    (ddrive 0.7.2) lib/ui/signup.ex:381: anonymous fn/4 in UI.Signup.handle_cast/2
12:42:14.323 [info] <0.2099.0> OS killing heart: 77442

**Comment by dominicletz** [comment]
Fixed in 9.1
