### ISSUE TITLE
Cannot drop drive, cannot create new drive

### ISSUE THREAD

**Issue by hansr** [diodechain/dDrive_Alpha_Program#27]
**OS:** Raspberry Pi 4 / Linux

**dDrive version:** 0.7.2 (patch: 0.8.0)

**Problem Description:**
My Pi is a peer (not owner) to four drives it has been invited to.  Because of this, it cannot create a new drive and it also cannot drop / leave a drive it has accepted.

**Expected Behavior:**
A) Re-introduce "drop drive" into the Web UI

B) Allow up to N "owned" drives (don't count accepted-drives towards drive limit or remove drive limit)

**Steps to Reproduce:**
1) Accept four drive invites
2) Observe that the "Create New Drive" main menu control is no longer available
3) Observe from the web menu that there is no "Drop Drive" control

**Comment by dominicletz** [comment]
Fixed in v0.10.1
