### ISSUE TITLE
Drives get out of sync and never recover

### ISSUE THREAD

**Issue by hansr** [diodechain/dDrive_Alpha_Program#46]
**System:** MacOS 10.15.4, Windows 10, dDrive version 0.7.2 p0.9.0

**Description:**
From time to time a peer will get out of sync with other peers (e.g. different # files, different storage size reported) and the peers never equalize.

**Steps to reproduce:**
* Unsure - Letz has access to a drive that has this situation

**Desired behavior:**
If stats are not aligned, they should get aligned by ensuring drives have same content.

**Comment by dominicletz** [comment]
This has been fixed in v0.9.2 . On the affected replicated drives, you've got to trigger "redownload files" using the legacy UI to fill up the missing files. After that all should be fine.
