### ISSUE TITLE
data grid columns are too narrow to read column names in dDrive Settings drive tab

### ISSUE THREAD

**Issue by intodiode** [diodechain/dDrive_Alpha_Program#9]
###     Operating system and version:
Linux raspberrypi 5.4.51;    armv7l

###     dDrive version:
0.7.2

###     Problem description:
After creating a new Drive, the 'dDrive Settings' drive tab shows empty gridview (no rows) but the column names are not readable due to columns being too narrow.
The narrow columns look like the following:
Pe|St|Ro|La|Re
-- | -- | -- | -- | --
 | | | | 
 | | | | 
 | | | | 
 | | | | 

The columns should not hide the text even though the grid has no data at this point.  Fully visible text for above cutoffs looks like the following:

Peer|Status|Role|Last Mutation|Remote Stats
-- | -- | -- | -- | --
 | | | | 
 | | | | 
 | | | | 
 | | | | 

###     Steps to reproduce:
Create new empty drive.  Open preferences.  Click the new drive's tab in 'dDrive Settings'. Notice the Grid view widget's columns are too narrow.

**Comment by hansr** [comment]
Also on MacOS and Windows

**Comment by dominicletz** [comment]
This will be fixed in v0.8.0 with the replacement of the old view with webviews.
